import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NowShowing from './components/NowShowing';
import axios from 'axios';

export default function Home(data) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <NowShowing data={data} />
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const cinestar = axios({
    method: 'GET',
    url: 'https://cinestar.pk/Browsing/Home/NowShowing'
  });
  const universalCinemas = axios({
    method: 'GET',
    url: 'https://universalcinemas.com/lahore/'
  });
  const [cinestarData, univCinemaData] = await Promise.all([
    cinestar, universalCinemas
  ]);
  return {
    props: { cinestar: cinestarData.data, universalCinemas: univCinemaData.data }
  };

}