import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ data }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {data.name}
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const response = await fetch("http://localhost:3000/api/hello");
  const data = await response.json();
  return {
    props: { data: data }
  };
}