import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import NowShowing from './components/NowShowing';
import axios from 'axios';
import { data } from 'autoprefixer';

export default function Home(data) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className="text-3xl font-bold underline">
          Hello world!
        </h1>
        <NowShowing data={data} />
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  // currently for lahore only
  const cinestar = axios({
    method: 'GET',
    url: 'https://cinestar.pk/Browsing/Home/NowShowing'
  });
  const universalCinemas = axios({
    method: 'GET',
    url: 'https://universalcinemas.com/lahore/'
  });
  const cueCinemas = axios({
    method: 'POST',
    url: 'https://cuecinemas.com/Browsing/Home/NowShowing'
  });
  const cinepax = axios({
    method: 'POST',
    url: 'https://www.cinepax.com/Home/GetNowShowingImages',
    data: {
      "strCityId": "4",
      "strLanguage": "0"
    }
  });
  
  
  const [cinestarData, univCinemaData, cueCinemasData, cinepaxData] = await Promise.all([
    cinestar, universalCinemas, cueCinemas, cinepax
  ]);
  return {
    props: { cinestar: cinestarData.data, universalCinemas: univCinemaData.data, cueCinemas: cueCinemasData.data, cinepax: cinepaxData.data }
  };

}